package KieRule;
import com.example.demoruleengine.MessageContent
import com.example.demoruleengine.Transaction

rule "Card Number: Only digits and 16 chars"

when
$t : Transaction(messageContent.onlyDigits(messageContent.getCardNumber())==true
              && messageContent.getCardNumber().length()==16);
then
$t.setCardNumberValidation(true);
System.out.println("CardNumberCheck");
end;

rule "Month and Year: Only digits and expiration check"

when
$t : Transaction(messageContent.compareDates(messageContent.getExpireMonth,messageContent.getExpireYear)
              && messageContent.onlyDigits(messageContent.getExpireMonth())==true
              && messageContent.onlyDigits(messageContent.getExpireYear())==true);
then
$t.setExpirationDateValidation(true);
System.out.println("Date is not expired");
end;

rule "Security code: Only 3 digits "

when
$t : Transaction(messageContent.onlyDigits(messageContent.getSecurityCode())==true
              && messageContent.getSecurityCode().length()==3);
then
$t.setSecurityCodeValidation(true);
System.out.println("CVV checked");
end;

